AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
  NewCops: enable
Metrics/BlockLength:
  Max: 40
Metrics/MethodLength:
  Max: 40
Metrics/ParameterLists:
  Max: 12
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Layout/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 18
Metrics/PerceivedComplexity:
  Max: 14
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - app/models/**/*
    - inia/**/*
Style/Documentation:
  Enabled: false

# Naming
Naming/FileName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Naming/VariableName:
  Enabled: false
